# serverless.yml

service: payroll-app 
provider:
  name: aws
  region: ap-southeast-1
  versionFunctions: false
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 10
  # TODO: apply least privillege access
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::c2pig-db/
    - Effect: Allow
      Action:
        - ec2:*
        - elasticfilesystem:*
      Resource: '*'

functions:
  app:
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    fileSystemConfig:
      # TODO: fix read-only issue in lambda
      localMountPath: /mnt/efs
      arn: arn:aws:elasticfilesystem:ap-southeast-1:198798184407:access-point/fsap-006ebe7ddfc876d9a
    vpc:
      securityGroupIds:
        - sg-cf3b04bd
      subnetIds:
        - subnet-93fa04db
plugins:
  - serverless-plugin-typescript 
package:
  exclude:
    - node_modules/aws-sdk/**
    - node_modules/serverless/**
    - node_modules/@serverless/**
    - node_modules/@types/**
