version: 2
build-steps: &build-steps
  steps:
    - checkout
    - restore_cache:
        keys: 
          - key-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    - run:
        name: install dependency
        command: yarn
    - save_cache:
        key: key-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
        paths:
          - node_modules/
    - run:
        name: build backend
        command: |
          yarn be:build
          yarn fe:build
    - persist_to_workspace:
        root: .
        paths:
          - public
          - dist

deploy-steps: &deploy-steps
  steps:
    - attach_workspace:
        at:  .
    - setup_remote_docker
    - run:
        name: debug env variable
        command: env
    - run:
        name: dockerize backend
        command: ./deployment/dockerize.sh
    - run:
        name: deploy frontend to s3 
        command: |
          aws s3 sync public/ s3://${S3_BUCKET}/
    - run:
        command: ls -la

jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: mhart/alpine-node:16
    <<: *build-steps
  deploy:
    working_directory: ~/workdir
    docker:
      - image: mhart/alpine-node:1
    environment:
      S3_BUCKET: "demo.c2pig.com"
    <<: *deploy-steps

workflows:
  version: 2
  ci:
    jobs:
      - approval:
          type: approval
      - build:
          requires:
            - approval
      - deploy:
          requires:
            - build
